alias rm="rm -i"
alias cp="cp -i"
alias mv="mv -i"
alias docker="sudo docker"
alias docker-compose="sudo /usr/local/bin/docker-compose"
alias ctop="sudo docker run --rm -ti --name=ctop -v /var/run/docker.sock:/var/run/docker.sock quay.io/vektorlab/ctop:latest"
