# export TERM=xterm-256color
export HISTSIZE=5000
export HISTCONTROL=ignoreboth:erasedups
export HISTIGNORE=?:??:???:exit:
export PIPENV_VENV_IN_PROJECT=true
export VIRTUALENV_ALWAYS_COPY=1
export PYTHON_CONFIGURE_OPTS="--enable-shared"
export RUBY_CONFIGURE_OPTS="--enable-shared"
export GPG_TTY=$(tty)
